-----SECUENCIA PELICULA------------
CREATE SEQUENCE SECUENCIA_PELICULA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_PELICULA
BEFORE INSERT ON PELICULAS
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_PELICULA.NEXTVAL INTO :NEW.ID_PELICULA FROM DUAL;
END;

------ SECUENCIA SALAS------------
CREATE SEQUENCE SECUENCIA_SALAS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_SALA
BEFORE INSERT ON SALAS
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_SALAS.NEXTVAL INTO :NEW.ID_SALA FROM DUAL;
END;
---------SECUENCIA PUESTO--------
CREATE SEQUENCE SECUENCIA_PUESTO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_PUESTO
BEFORE INSERT ON PUESTOS
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_PUESTO.NEXTVAL INTO :NEW.ID_PUESTO FROM DUAL;
END;

-------------SECUENCIA HORARIOS---------
CREATE SEQUENCE SECUENCIA_HORARIOS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_HORARIOS
BEFORE INSERT ON HORARIOS
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_HORARIOS.NEXTVAL INTO :NEW.ID_HORARIO FROM DUAL;
END;
---------------RESERVAS---------------
CREATE SEQUENCE SECUENCIA_RESERVAS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_RESERVAS
BEFORE INSERT ON RESERVAS
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_RESERVAS.NEXTVAL INTO :NEW.ID_RESERVA FROM DUAL;
END;
------------------SECUENCIA INVENTARIO----------
CREATE SEQUENCE SECUENCIA_INVENTARIOS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_INVENTARIOS
BEFORE INSERT ON INVENTARIO
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_INVENTARIOS.NEXTVAL INTO :NEW.ID_INVENTARIO FROM DUAL;
END;
----------SECUENCIA FACTURA--------------
CREATE SEQUENCE SECUENCIA_FACTURAS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_INSERT_FACTURAS
BEFORE INSERT ON FACTURA
FOR EACH ROW
BEGIN
   SELECT SECUENCIA_FACTURAS.NEXTVAL INTO :NEW.ID_FACTURA FROM DUAL;
END;



-- CREACIÓN TABLA PELICULAS
CREATE TABLE PELICULAS(
   ID_PELICULA  INTEGER NOT NULL PRIMARY KEY,
   NOMBRE  VARCHAR2(80) NOT NULL,
   DIRECTOR VARCHAR2(80) NOT NULL,
   GENERO  VARCHAR2(80) NOT NULL,
   FECHA_ESTRENO DATE NOT NULL,
   CLASIFICACION  VARCHAR2(80) NOT NULL
);
--CREACIÓN TABLA SALA
CREATE TABLE SALAS(
   ID_SALA INTEGER NOT NULL PRIMARY KEY,
   NUMERO_SALA NUMBER NOT NULL,
   CAPACIDAD NUMBER NOT NULL,
   TIPO_PANTALLA VARCHAR2(80) NOT NULL
);
--CREACION TABLA CLIENTE
CREATE TABLE CLIENTES(
   NUMERO_CEDULA  INTEGER NOT NULL PRIMARY KEY,
   NOMBRE  VARCHAR2(80) NOT NULL,
   APELLIDO1 VARCHAR2(80) NOT NULL,
   APELLIDO2  VARCHAR2(80) NOT NULL,
   EMAIL  VARCHAR2(80) NOT NULL,
   CONTRASENA  VARCHAR2(12) NOT NULL
);
--CREACION TABLA PUESTO
    CREATE TABLE PUESTO(
    ID_PUESTO INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(80)NOT NULL
);    
    
--CREACIÓN TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
   NUMERO_CEDULA_E INTEGER NOT NULL PRIMARY KEY,
   NOMBRE VARCHAR2(80) NOT NULL,
   APELLIDO1 VARCHAR2(80) NOT NULL,
   APELLIDO2  VARCHAR2(80) NOT NULL,
   EMAIL  VARCHAR2(80) NOT NULL,
   DIRECCION VARCHAR2(80) NOT NULL,
   SALARIO DECIMAL (10,2) NOT NULL,
   ID_PUESTO INTEGER NOT NULL,
   CONSTRAINT FK_ID_PUESTO FOREIGN KEY (ID_PUESTO)REFERENCES PUESTO(ID_PUESTO)
);
-- CREACIÓN TABLA HORARIOS
CREATE TABLE HORARIOS(
   ID_HORARIO INTEGER NOT NULL PRIMARY KEY,
   ID_PELICULA INTEGER NOT NULL,
    ID_SALA INTEGER NOT NULL,
    FECHA_HORA DATE NOT NULL,
    CONSTRAINT FK_PELI FOREIGN KEY (ID_PELICULA)REFERENCES PELICULAS(ID_PELICULA),
    CONSTRAINT FK_SALA FOREIGN KEY (ID_SALA)REFERENCES SALAS(ID_SALA)
   
);
--CREACIÓN TABLA DE RESERVAS
CREATE TABLE RESERVAS(
   ID_RESERVA INTEGER NOT NULL PRIMARY KEY,
   NUMERO_CEDULA INTEGER NOT NULL,
    ID_HORARIO INTEGER NOT NULL,
    CANTIDAD_BOLETOS NUMBER,
    CONSTRAINT FK_CEDU FOREIGN KEY (NUMERO_CEDULA)REFERENCES CLIENTES(NUMERO_CEDULA),
    CONSTRAINT FK_HORA FOREIGN KEY (ID_HORARIO)REFERENCES HORARIOS(ID_HORARIO)
);
--CREACIÓN TABLA INVENTARIO
CREATE TABLE INVENTARIO(
   ID_INVENTARIO INTEGER NOT NULL PRIMARY KEY,
   PRODUCTO VARCHAR2(80)NOT NULL,
   CANTIDAD NUMBER NOT NULL,
   PRECIO DECIMAL (10,2) NOT NULL,
    ID_HORARIO INTEGER NOT NULL,
    CONSTRAINT FK_HORA_I FOREIGN KEY (ID_HORARIO)REFERENCES HORARIOS(ID_HORARIO)
);
--CREACIÓN TABLA FACTURA
CREATE TABLE FACTURA(
   ID_FACTURA INTEGER NOT NULL PRIMARY KEY,
  NUMERO_CEDULA INTEGER NOT NULL,
    ID_HORARIO INTEGER NOT NULL,
    METODO_PAGO VARCHAR2(80)NOT NULL,
    ESTADO VARCHAR2(80)NOT NULL,
    CONSTRAINT FK_CLI FOREIGN KEY (NUMERO_CEDULA)REFERENCES CLIENTES(NUMERO_CEDULA),
    CONSTRAINT FK_HORA_F FOREIGN KEY (ID_HORARIO)REFERENCES HORARIOS(ID_HORARIO)
);






